const PLANET_DATA = {
  sun: {
    name: "The Sun",
    tagline: "Yellow Dwarf Star (G2V)",
    description: "The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core. The Sun radiates this energy mainly as light, ultraviolet, and infrared radiation, providing the primary energy source for life on Earth.",
    image: "./assets/sun.png",
    color: "#ffaa00",
    stats: {
      mass: "1.989 × 10^30 kg (333,000 Earths)",
      diameter: "1,392,700 km",
      surfaceTemp: "5,500 °C",
      coreTemp: "15,000,000 °C",
      gravity: "274 m/s² (28x Earth)",
      rotation: "25-35 Earth Days",
      composition: "73% Hydrogen, 25% Helium, 2% Other"
    },
    funFacts: [
      "One million Earths could fit inside the Sun if it were hollow.",
      "The Sun travels at 220 km/s, taking about 230 million years to orbit the Milky Way center.",
      "The light from the Sun takes approximately 8 minutes and 20 seconds to reach Earth."
    ],
    orbital: {
      distance: 0,
      period: 0,
      speed: 0,
      size: 25, // Visual scale radius
      semiMajor: 0
    }
  },
  mercury: {
    name: "Mercury",
    tagline: "The Swift Planet",
    description: "Mercury is the smallest planet in our solar system and the nearest to the Sun. Due to its lack of a substantial atmosphere to trap heat, it experiences the most extreme temperature fluctuations in the solar system, ranging from bitterly cold nights to scorching days.",
    image: "./assets/mercury.png",
    color: "#888899",
    stats: {
      mass: "3.285 × 10^23 kg (0.055 Earths)",
      diameter: "4,879 km",
      surfaceTemp: "-180 °C to 430 °C",
      gravity: "3.7 m/s² (0.38x Earth)",
      rotation: "59 Earth Days",
      distanceFromSun: "57.9 Million km",
      composition: "Metallic Iron-Nickel Core, Silicate Crust"
    },
    funFacts: [
      "A year on Mercury is just 88 Earth days, but a single day-night cycle takes 176 Earth days!",
      "Mercury is the second densest planet in the solar system, with a massive metallic core making up 85% of its radius.",
      "Despite being closest to the Sun, it is not the hottest planet—that title belongs to Venus."
    ],
    orbital: {
      distance: 42, // Adjusted for display visibility
      period: 88,
      speed: 0.04,
      size: 2.2,
      semiMajor: 0.39
    }
  },
  venus: {
    name: "Venus",
    tagline: "Earth's Toxic Twin",
    description: "Venus is the second planet from the Sun and our closest planetary neighbor. It is shrouded in a crushing, toxic atmosphere of carbon dioxide with clouds of sulfuric acid. This atmosphere triggers a runaway greenhouse effect, making its surface hot enough to melt lead.",
    image: "./assets/venus.png",
    color: "#e39a3b",
    stats: {
      mass: "4.867 × 10^24 kg (0.815 Earths)",
      diameter: "12,104 km",
      surfaceTemp: "465 °C (Constant)",
      gravity: "8.87 m/s² (0.9x Earth)",
      rotation: "243 Earth Days (Retrograde)",
      distanceFromSun: "108.2 Million km",
      composition: "Carbon Dioxide (96.5%), Nitrogen (3.5%) atmosphere"
    },
    funFacts: [
      "Venus rotates backwards on its axis compared to most planets, meaning the Sun rises in the west.",
      "Soviet spacecraft Venera 13 survived on Venus's crushing surface for only 127 minutes before being destroyed.",
      "Venus is the brightest natural object in Earth's night sky after the Moon, casting shadows under perfect conditions."
    ],
    orbital: {
      distance: 60,
      period: 224.7,
      speed: 0.015,
      size: 4.8,
      semiMajor: 0.72
    }
  },
  earth: {
    name: "Earth",
    tagline: "The Oasis of Life",
    description: "Earth is our home planet and the only astronomical object known to harbor life. It is the third planet from the Sun, situated in the circumstellar habitable zone. Its abundant liquid water, temperate climate, active plate tectonics, and shielding magnetic field create a perfect cradle for biosphere complexity.",
    image: "./assets/earth.png",
    color: "#2b82c9",
    stats: {
      mass: "5.972 × 10^24 kg",
      diameter: "12,742 km",
      surfaceTemp: "-89 °C to 58 °C",
      gravity: "9.81 m/s² (1.0x Earth)",
      rotation: "24 Hours (23h 56m)",
      distanceFromSun: "149.6 Million km",
      composition: "Nitrogen (78%), Oxygen (21%), Argon (0.9%), CO2"
    },
    funFacts: [
      "Earth is the only planet not named after a mythological god or goddess; its name comes from Old English/German meaning 'ground'.",
      "Earth's magnetic field is generated by a dynamo effect in its liquid iron outer core, shielding us from solar winds.",
      "The planet is not a perfect sphere; centrifugal force from rotation causes an equatorial bulge."
    ],
    orbital: {
      distance: 82,
      period: 365.25,
      speed: 0.01,
      size: 5.0,
      semiMajor: 1.0
    }
  },
  mars: {
    name: "Mars",
    tagline: "The Red Planet",
    description: "Mars is a cold, dry, desert world with a very thin carbon dioxide atmosphere. It has iron minerals in its soil that oxidize (rust), giving the entire landscape its signature reddish tint. Mars features massive ancient volcanoes, deep canyons, and polar ice caps composed of water and dry ice.",
    image: "./assets/mars.png",
    color: "#c1440e",
    stats: {
      mass: "6.390 × 10^23 kg (0.107 Earths)",
      diameter: "6,779 km",
      surfaceTemp: "-140 °C to 20 °C",
      gravity: "3.71 m/s² (0.38x Earth)",
      rotation: "24.6 Hours",
      distanceFromSun: "227.9 Million km",
      composition: "Carbon Dioxide (95.3%), Nitrogen (2.7%), Argon"
    },
    funFacts: [
      "Mars is home to Olympus Mons, the largest volcano in the Solar System, three times taller than Mount Everest.",
      "Liquid water cannot exist on the surface of Mars for long due to the extremely low atmospheric pressure.",
      "Mars has two small lumpy moons, Phobos and Deimos, which are believed to be captured main-belt asteroids."
    ],
    orbital: {
      distance: 110,
      period: 687,
      speed: 0.008,
      size: 3.2,
      semiMajor: 1.52
    }
  },
  jupiter: {
    name: "Jupiter",
    tagline: "The King of Planets",
    description: "Jupiter is the largest planet in our solar system—a massive gas giant more than twice as massive as all the other planets combined. It is famous for its colorful, swirling cloud bands of ammonia and water, and the Great Red Spot, a colossal atmospheric storm that has raged for centuries.",
    image: "./assets/jupiter.png",
    color: "#cca270",
    stats: {
      mass: "1.898 × 10^27 kg (318 Earths)",
      diameter: "139,820 km",
      surfaceTemp: "-110 °C (Cloud tops)",
      gravity: "24.79 m/s² (2.53x Earth)",
      rotation: "9.9 Hours",
      distanceFromSun: "778.5 Million km",
      composition: "90% Hydrogen, 10% Helium (Similar to a star)"
    },
    funFacts: [
      "Jupiter acts as a cosmic shield for Earth, its powerful gravity deflecting or capturing many incoming comets and asteroids.",
      "The Great Red Spot is a high-pressure storm wider than planet Earth itself, active since at least the 17th century.",
      "Jupiter has 95 officially recognized moons, including Ganymede, the largest moon in the Solar System, which is larger than Mercury."
    ],
    orbital: {
      distance: 155,
      period: 4333,
      speed: 0.004,
      size: 11.5,
      semiMajor: 5.20
    }
  },
  saturn: {
    name: "Saturn",
    tagline: "The Jewel of the Solar System",
    description: "Saturn is a magnificent gas giant decorated with a vast, glittering system of rings. While other outer planets have rings, none are as complex, reflective, or expansive as Saturn's. It is composed mostly of hydrogen and helium and has a density lower than water.",
    image: "./assets/saturn.png",
    color: "#e2bf7d",
    stats: {
      mass: "5.683 × 10^26 kg (95 Earths)",
      diameter: "116,460 km",
      surfaceTemp: "-140 °C",
      gravity: "10.44 m/s² (1.06x Earth)",
      rotation: "10.7 Hours",
      distanceFromSun: "1.43 Billion km",
      composition: "Hydrogen, Helium, with trace methane and water"
    },
    funFacts: [
      "Saturn is the least dense planet in the Solar System; if you could find a bathtub big enough, Saturn would float in it!",
      "Saturn's rings are not solid, but made of billions of individual particles of water ice, dust, and rock, ranging from tiny grains to mountain-sized chunks.",
      "Its moon Titan is the only moon in the solar system with a dense atmosphere and liquid hydrocarbon lakes on its surface."
    ],
    orbital: {
      distance: 210,
      period: 10759,
      speed: 0.002,
      size: 9.8,
      semiMajor: 9.58
    }
  },
  uranus: {
    name: "Uranus",
    tagline: "The Bullseye Planet",
    description: "Uranus is an ice giant with a pale cyan-blue color caused by atmospheric methane absorbing red light. It is unique for its extreme axial tilt of 98 degrees, meaning it literally rolls on its side as it orbits the Sun, likely due to a cataclysmic collision early in its history.",
    image: "./assets/uranus.png",
    color: "#aae2e6",
    stats: {
      mass: "8.681 × 10^25 kg (14.5 Earths)",
      diameter: "50,724 km",
      surfaceTemp: "-195 °C",
      gravity: "8.69 m/s² (0.89x Earth)",
      rotation: "17.2 Hours (Retrograde)",
      distanceFromSun: "2.87 Billion km",
      composition: "Water, Ammonia, Methane Ices; Hydrogen/Helium Gas"
    },
    funFacts: [
      "Because of Uranus's extreme tilt, a single season lasts 21 Earth years, during which one pole gets continuous sunlight while the other is in darkness.",
      "Uranus was the first planet discovered in the modern era, spotted by William Herschel in 1781 using a telescope.",
      "Like Saturn, Uranus has rings, but they are dark, narrow, and oriented vertically relative to the ecliptic plane."
    ],
    orbital: {
      distance: 260,
      period: 30687,
      speed: 0.001,
      size: 7.2,
      semiMajor: 19.20
    }
  },
  neptune: {
    name: "Neptune",
    tagline: "The Windswept Giant",
    description: "Neptune is the most distant planet in our solar system—a dark, cold ice giant swept by supersonic winds. It is a deep cobalt blue and features active, dark storm systems. Neptune was the first planet discovered through mathematical predictions rather than empirical observation.",
    image: "./assets/neptune.png",
    color: "#274687",
    stats: {
      mass: "1.024 × 10^26 kg (17 Earths)",
      diameter: "49,244 km",
      surfaceTemp: "-200 °C",
      gravity: "11.15 m/s² (1.14x Earth)",
      rotation: "16.1 Hours",
      distanceFromSun: "4.5 Billion km",
      composition: "Water, Ammonia, Methane Ices; Hydrogen, Helium, Methane gas"
    },
    funFacts: [
      "Neptune has the fastest wind speeds recorded in the Solar System, reaching up to 2,100 km/h—faster than the speed of sound!",
      "Neptune's largest moon Triton orbits the planet in a retrograde direction (opposite to the planet's spin), suggesting it was captured from the Kuiper Belt.",
      "Because of Pluto's elliptical orbit, Pluto is occasionally closer to the Sun than Neptune is."
    ],
    orbital: {
      distance: 310,
      period: 60190,
      speed: 0.0007,
      size: 7.0,
      semiMajor: 30.05
    }
  }
};

// Export to window object for global script access
window.PLANET_DATA = PLANET_DATA;
